### ISSUE TITLE
Fold in inherited class

### ISSUE THREAD

**Issue by apmanol** [edouarda/brigand#96] opened 2015-12-02 08:52 UTC
Hello, 

I have noticed the following issue:
```cpp
struct a{};
struct b{};
struct c{};
struct mylist : brigand::list<a,b,c,c>{};
using mylist1 = brigand::list<a,b,c,c>;

using f_class_ = brigand::if_<std::is_class<brigand::_element>,
                         brigand::next<brigand::_state>,
                         brigand::_state>;

  static_assert(brigand::fold<mylist1, brigand::uint32_t<0>, f_class_>::value == 4, "error");
 //fails here
  static_assert(brigand::fold<mylist, brigand::uint32_t<0>, f_class_>::value == 4, "error"); 

```

On the other hand the boost MPL supports this kind of traversing.

**Comment by edouarda** [comment] 2015-12-02 10:48
If I understand correctly, we need brigand::fold to somehow inspect mylist, see the underlying brigand::list and iterate on it. As is, fold sees only a "mylist" object, doesn't see the template parameter and therefore fails.

Is that the problem?

**Comment by edouarda** [comment] 2015-12-02 10:51
One way to solve it, which I don't like to much is to add a method in brigand::list which returns the type, if brigand::fold sees the method it does a decltype on it and iterate on that.

**Comment by jfalcou** [comment] 2015-12-02 10:52
Yes

I think this is related to the extension problem.

One fix could be to ave brignad list to have an internal

using brigand_type = lis<Ts...>

Then all algorithms match either L<T...> and if not, try to find a internal brigand_type inside and apply itself to it.

Now if you inhert rom brigand::list<>, you have your using and it works

**Comment by edouarda** [comment] 2015-12-02 10:53
We had the same idea, but not sure all compilers will find the using. And by "not all the compilers" I mean Visual Studio.

**Comment by jfalcou** [comment] 2015-12-02 10:57
It should work. If it doesnt work, we can have a explicit sequence_of<T> metafunction

**Comment by edouarda** [comment] 2015-12-02 10:57
I think it's best to have sequence_of that way people can customize it for their own type.

**Comment by jfalcou** [comment] 2015-12-02 10:59
and we solve our adaptation issue

**Comment by edouarda** [comment] 2015-12-02 11:45
Да.

**Comment by porkybrain** [comment] 2016-03-11 10:21
MSVC12 usually dies on `using x = anything<>` so the empty list case would not work. A nested metafunction should work on MSVC12 but, to be honest I don't really see the use case but I'm not a boost.MPL guy (was late to the party). 
Alternatively you could make the user wrap the list in a wrapper which provides the metafunction:

```C++
template<typename T>
struct export : T{
   using brigand_exported = T;
};

struct mylist : export<list<a,b,c,c>>{};
```

that way its an opt in. That would of course not be a seamless of an MPL migration, however existing code will be deriving from an MPL list and not a brigand::list so we will be breaking stuff any way (we can't put a using in the MPL list). `export<boost::mpl::list<a,b,c>>` would work on the other hand.

**Comment by edouarda** [comment] 2016-03-14 07:25
That's an alternative to Joel suggestion. In any case we need to change all algorithms.

**Comment by porkybrain** [comment] 2016-08-16 20:04
I don't see any way to do this without SFINAE which would kill speed.

**Comment by edouarda** [comment] 2016-08-16 21:20
Maybe we could have a "slow" version of the function for this purpose?

**Comment by porkybrain** [comment] 2016-08-17 08:12
That would be an option I am comfortable with. I wonder how many people it affects. Maybe call it legacy_fold.

**Comment by edouarda** [comment] 2016-08-17 09:24
The other way would be to ask for something like

```cpp
  static_assert(brigand::fold<brigand::adapt(mylist), brigand::uint32_t<0>, f_class_>::value == 4, "error"); 
```

**Comment by brunocodutra** [comment] 2016-08-17 09:31
Don't mind me asking, but why would you need something like that? MPL
allows this because its concept of a List is based on a type's nested
members. What is Brigand's concept of a list? I was under the impression it
were any alias to an specialization of any class or union template which
takes only types as arguments, so a type that inherits a List would simply
not be a List and thus not be foldable.

**Comment by porkybrain** [comment] 2016-08-17 10:30
we could also just provide an alias which unpacks an MPL list which is hiding in a base class into a brigand list. In my opinion there is no way to make MPL work seamlessly in this respect and not take a huge performance hit. Therefore if we are expecting people porting from MPL who are using inheritance to change something than dropping their list into an unpacker before passing it to fold (or any other algorithm for that matter, its not just fold) seems like the way to go.

**Comment by edouarda** [comment] 2016-08-17 10:33
@brunocodutra We want to help users to migrate from Boost.MPL legacy code.

@porkybrain I think it's the best solution as well.

**Comment by brunocodutra** [comment] 2016-08-17 11:06
> We want to help users to migrate from Boost.MPL legacy code.

Right of course, but one can only go so far to maintain backwards compatibility with MPL. See the problem is that there doesn't seem to be a precise definition for the concept of a List in Brigand, nor for the concept of a Callable for what's worth. Why would a type that inherits from a List be foldable but not reversible, for example? 

In my humble opinion you are going down a dangerous path, because eventually this ad hoc patching to make things seem to just work might backfire.

**Comment by porkybrain** [comment] 2016-08-17 11:30
@brunocodutra yes you are right, concentrating on fold is distracting, this needs to be an all or nothing approach. The concept of a list in brigand is super lax, any template with no non type parameters is a list, which is a good thing in my mind. Lazy callable is anything with a nested type alias and eager callable is anything that fits the signature of bind.

**Comment by brunocodutra** [comment] 2016-08-17 11:42
> any template with no non type parameters is a list

Are the following Lists then?

~~~{.cpp}
template<typename> struct fixed_size_list {};
using list = fixed_size_list<void>;
~~~

~~~{.cpp}
template<typename = void, typename = void*> struct fixed_size_list_with_default_contents {};
using list = fixed_size_list_with_default_contents<>; // size<list>::value == 2
~~~

These used to be valid Lists in Metal, but the overhead to make it behave consistently in every situation was so great that I decided to make Lists strictier by requiring that they be specializations of `metal::list`. Could not be happier with this decision.

**Comment by jfalcou** [comment] 2016-08-17 11:44
Can't we just have a `from_mpl<T>` that do the once-but-painful of returning a list of `mpl::as_vector<T>`  ?

**Comment by porkybrain** [comment] 2016-08-17 11:59
@brunocodutra you may have a point that types with defaulted parameters mess stuff up. On the other hand there are a lot of "list" types out there, most importantly probably the MPL::list which we should still support. I guess passing something in as a list which has default parameters is undefined behavior for now.
@jfalcou that is essentially my suggestion ;)

**Comment by brunocodutra** [comment] 2016-08-17 12:13
> On the other hand there are a lot of "list" types out there, most importantly probably the MPL::list which we should still support

The problem of `mpl::list` is that it's type is implementation defined, that is, strictly speaking the user is not allowed to partialy specialize a template for `mpl::list`. The only possible solution to this conondrum is to provide a `brigand::from_mpl_list` which relies on [`mpl::apply_wrap` ](http://www.boost.org/doc/libs/1_61_0/libs/mpl/doc/refmanual/apply-wrap.html) or similar to make a `brigand::list`.

**Comment by jfalcou** [comment] 2016-09-20 17:57
After some reflexions, this bug is actually coming from a MPL-style usage of Brigand, thign we want ot go away from. I woudl temptatively say it's probably a `nofix` issue.

If nobody disagree, I'll close it later this week.

**Comment by apmanol** [comment] 2016-09-22 06:24
Indeed that was the case, an attempt to replace the use of Boost.mpl with Brigand.

Nevertheless your point is clear.

**Closed** 2016-09-22 12:39 UTC
Labels: bug, wontfix
